version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 18
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
plugins:
  fixme:
    enabled: false
  rubocop:
    enabled: true
    config: .rubocop.yml
    exclude_fingerprints:
    - c46545507dd9c0ee0b06ade73f99824e
    - a03b9bf2b9fdbfdab660422385265cd0
  brakeman:
    enabled: true
    exclude_fingerprints:
    - dddc38ecdf09b41a514d23ca5f1fcc94c5cf7a6b7c16678bcb7cb0b4435e47d9
    - 4114d80e9cc178232bb96981ad86242e6fe5358be6d84033bf86184d947030ad
    - 829226bd25ac3f5f3281766f8a14d2934a345bce7e456a8bf12d8c841de21c71
    - c3eb48478c89591bdf3c9d8b27b3d9b8a875e34c2bb61232485d684c455c90b2
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 19
  bundler-audit:
    enabled: true
exclude_patterns:
- "app/controllers/concerns/*_doc.rb"
- "public/api"
- "lib/tasks"
- "public/coverage"
- "test"
- "public/javascripts"
- "lib/sample_data.rb"
- "app/controllers/*.rb"
- "!app/controllers/application_controller.rb"
- "db/migrate"
- "app/graphql"
- "doc"
- "app/models/ability.rb"
- "app/models/admin_ability.rb"
- "config/initializers/rails_admin.rb"
- ".codeclimate.yml"
- "data"
- "**.js"
- "public/viber/bigtext.js"
