languages:
  Ruby: true
  JavaScript: false
engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
  rubocop:
    enabled: true
    config: .rubocop.yml
  brakeman:
    enabled: true
    exclude_fingerprints:
    - dddc38ecdf09b41a514d23ca5f1fcc94c5cf7a6b7c16678bcb7cb0b4435e47d9
    - 4114d80e9cc178232bb96981ad86242e6fe5358be6d84033bf86184d947030ad
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  bundler-audit:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- "app/controllers/concerns/*_doc.rb"
- "public/api"
- "lib/tasks"
- "public/coverage"
- "test"
- "public/javascripts"
- "lib/sample_data.rb"
- "app/controllers/*.rb"
- "!app/controllers/application_controller.rb"
- "db/migrate"
- "app/graphql"
- "doc"
- "app/models/ability.rb"
- ".codeclimate.yml"
