source 'https://rubygems.org'

group :development, :test do
  gem 'byebug'
  gem 'rubocop', '0.49.0'
  gem 'rails-graphql-generator'
  gem 'parallel_tests'
end

group :development do
  gem 'web-console', '~> 2.0'
end

# Use pender from git
gem 'pender_client', git: 'https://github.com/meedan/pender-client.git', ref: 'e8eca00'

gem 'logstash-logger'
gem 'rails', '4.2.7.1'
gem 'sqlite3'
gem 'pg', '~> 0.15'
gem 'pg_application_name'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'cancancan', '~> 1.10'
gem 'bootstrap-sass', '~> 3.2.0.0'
gem 'carrierwave', '~> 0.9'
gem 'phony_rails'
gem 'webmock'
gem 'mocha'
gem 'simplecov', '0.13.0', require: false, group: :test
gem 'simplecov-console', require: false, group: :test
gem 'railroady'
gem 'airbrake', '4.3.3'
gem 'codeclimate-test-reporter', '1.0.8', group: :test, require: nil
gem 'awesome_print', require: false, group: :development
gem 'gem-licenses'
gem 'thin'
gem 'swagger-docs', '0.1.9'
gem 'responders'
gem 'htmlentities', require: false, group: :development
gem 'graphql', '1.8.0.pre10'
gem 'devise'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-slack'
gem 'elasticsearch', '~> 6.x'
gem 'elasticsearch-api', '~> 6.x'
gem 'elasticsearch-transport', '~> 6.x'
gem 'elasticsearch-model', '0.1.9'
gem 'elasticsearch-persistence', '0.1.9', require: 'elasticsearch/persistence/model'
gem 'paper_trail'
gem 'graphiql-rails', git: 'https://github.com/meedan/graphiql-rails.git', ref: '8db0eac'
gem 'graphql-formatter'
gem 'nokogiri', '1.8.5'
gem 'mini_magick'
gem 'puma'
gem 'rack-cors', :require => 'rack/cors'
gem 'sidekiq'
gem 'sidekiq-limit_fetch'
gem 'sinatra'
gem 'pusher'
gem 'redis-namespace'
gem 'file_validators'
gem 'clamav-client'
gem 'filesize'
gem 'rest-client'
gem 'rails_admin', '~> 1.3.0'
gem 'transifex-interface-ruby', git: 'https://github.com/meedan/transifex-interface-ruby.git'
gem 'http_accept_language', git: 'https://github.com/iain/http_accept_language.git'
gem 'i18n-generators'
gem 'rails-i18n', git: 'https://github.com/svenfuchs/rails-i18n.git', branch: 'rails-4-x', ref: 'f8c83ec'
gem 'alegre_client', git: 'https://github.com/meedan/alegre-client.git', ref: 'a78f321'
gem 'devise-i18n'
gem 'devise_invitable', '~> 1.7.0'
gem 'ruby-cldr'
gem 'twitter'
gem 'request_store'
gem 'geojsonlint'
gem 'jsonpath', '~> 0.8.8'
gem 'graphql-batch'
gem 'google-protobuf', '3.2.0'
gem 'concurrent-ruby', require: 'concurrent'
gem 'rails_admin_material'
gem 'apollo-tracing', '1.5.0'
gem 'rubyzip', '1.2.2'
gem 'rack-protection', '1.5.5'
gem 'loofah', '2.2.3'
gem 'deep_cloneable', '~> 2.3.0'
gem 'test_after_commit', group: :test
gem 'rails-html-sanitizer', '1.0.4'
gem 'minitest-retry'
gem 'sprockets', '3.7.2'
gem 'pghero'
gem 'pg_query', '>= 0.9.0'
gem 'multi_json', '1.12.2'
gem 'json-schema'
gem 'ffi', '1.9.24'
gem 'google_drive'
gem 'activerecord-import'
gem 'redis-rails'
