source 'https://rubygems.org'

group :development, :test do
  gem 'byebug'
  gem 'rubocop'
  gem 'rails-graphql-generator'
end

group :development do
  gem 'web-console', '~> 2.0'
end

# Use pender from git
gem 'pender_client', git: "https://github.com/meedan/pender-client.git"

gem 'logstash-logger'
gem 'rails', '4.2.7.1'
gem 'sqlite3'
gem 'pg', '~> 0.15'
gem 'pg_application_name'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'cancancan', '~> 1.10'
gem 'bootstrap-sass', '~> 3.2.0.0'
gem 'carrierwave', '~> 0.9'
gem 'phony_rails'
gem 'webmock'
gem 'mocha'
gem 'simplecov', require: false, group: :test
gem 'railroady'
gem 'airbrake', '4.3.3'
gem 'codeclimate-test-reporter', '0.6.0', group: :test, require: nil
gem 'awesome_print', require: false, group: :development
gem 'gem-licenses'
gem 'thin'
gem 'swagger-docs', '0.1.9'
gem 'responders'
gem 'htmlentities', require: false, group: :development
gem 'graphql', '0.14.0'
gem 'graphql-relay', '0.10.0'
gem 'devise'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-slack'
gem 'elasticsearch', '2.0.0'
gem 'elasticsearch-api', '2.0.0'
gem 'elasticsearch-transport', '2.0.0'
gem 'elasticsearch-model', '0.1.9'
gem 'elasticsearch-persistence', '0.1.9', require: 'elasticsearch/persistence/model'
gem 'paper_trail'
gem 'graphiql-rails', git: 'https://github.com/caiosba/graphiql-rails.git', ref: 'd03dd94'
gem 'graphql-formatter'
gem 'nokogiri', '1.7.2'
gem 'mini_magick'
gem 'puma'
gem 'rack-cors', :require => 'rack/cors'
gem 'sidekiq'
gem 'sidekiq-limit_fetch'
gem 'sinatra'
gem 'pusher'
gem 'redis-namespace'
gem 'newrelic_rpm'
gem 'file_validators'
gem 'clamav-client'
gem 'filesize'
gem 'rest-client'
gem 'rails_admin', '~> 1.0'
gem 'transifex-interface-ruby'
gem 'http_accept_language', git: 'https://github.com/iain/http_accept_language.git'
gem 'i18n-generators'
gem 'rails-i18n', git: 'https://github.com/svenfuchs/rails-i18n.git', branch: 'rails-4-x', ref: 'f8c83ec'
gem 'alegre_client', git: 'https://github.com/meedan/alegre-client.git', ref: '31f8ab5'
gem 'devise-i18n'
gem 'ruby-cldr'
gem 'twitter'
