name: Build and Run Tests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - develop

env:
  CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"

jobs:
  functional-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Enviroments
      run: |
        export RECORD_RUNTIME=true
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        export LANGUAGE=C.UTF-8
        export PATH=/root/.local/bin:$PATH
        rm -rf tmp/cache tmp/cache1 tmp/cache2 tmp/cache3 tmp/cache4 tmp/cache5 && mkdir -p tmp/cache tmp/cache1 tmp/cache2 tmp/cache3 tmp/cache4 tmp/cache5

    - name: Set up Configuration Files
      run: |
        cp config/config.yml.example config/config.yml
        cp config/database.yml.example config/database.yml
        cp config/sidekiq.yml.example config/sidekiq.yml
        cp config/credentials.json.example config/credentials.json
        cp config/sidekiq-test.yml.example config/sidekiq-test.yml

    - name: Build Docker Container
      run: |
        docker compose build
    - name: Run syntax checks
      run: |
        docker compose run api bash -c 'touch /tmp/no-syntax-errors && find app lib config -name *.rb -exec bash -c "ruby -c {} >/dev/null || rm /tmp/no-syntax-errors" ";" && ls /tmp/no-syntax-errors'
    - name: Run Container
      run: docker compose -f docker-compose.yml -f docker-test.yml up -d

    - name: Wait for the server to be ready
      run: |
        tail -f log/test.log &
        until curl --silent -I -f --fail http://localhost:3000 ; do printf .; sleep 1; done
    - name: Set up parallel environment
      run: docker compose exec -T api test/setup-parallel-env.sh

    - name: Precompile Assets
      run: docker compose exec -T api bundle exec rake assets:precompile

    - name: Prepare Parallel Runtime Log
      run: |
        sleep 10
        touch tmp/parallel_runtime_test.log
        chmod +w tmp/parallel_runtime_test.log

    - name: Run Functional Tests
      id: functional-tests
      env:
        TEST_RETRY_COUNT: 3
      run: |
        docker compose exec -e TEST_RETRY_COUNT=$TEST_RETRY_COUNT -T -e PATTERN='models mailers integration workers lib contract' api test/run-tests.sh

    - name: After Functional Test
      env:
        GITHUB_EVENT: ${{ github.event_name}}
        GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TEST_RESULT: ${{ steps.functional-tests.outcome}}
        GITHUB_BUILD_NUMBER: ${{ github.run_number }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
        GITHUB_JOB_NAME: ${{ github.job }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        AWS_REGION: eu-west-1
      run:  |
        docker compose exec -T -e GIT_BRANCH=$GIT_BRANCH \
        -e GITHUB_EVENT=$GITHUB_EVENT \
        -e GITHUB_TEST_RESULT=$GITHUB_TEST_RESULT \
        -e GITHUB_REPO=$GITHUB_REPO \
        -e GITHUB_BUILD_NUMBER=$GITHUB_BUILD_NUMBER \
        -e GIT_COMMIT_SHA=$GITHUB_COMMIT_SHA \
        -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID \
        -e GITHUB_JOB_NAME=$GITHUB_JOB_NAME \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e ROLE_TO_ASSUME=$AWS_ROLE_TO_ASSUME \
        -e AWS_REGION=$AWS_REGION \
        -e AWS_CONFIG_FILE=/app/credentials api test/test-coverage.sh


  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: set up enviromnts
      run: |
        export RECORD_RUNTIME=true
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        export LANGUAGE=C.UTF-8
        export PATH=/root/.local/bin:$PATH
        rm -rf tmp/cache tmp/cache1 tmp/cache2 tmp/cache3 tmp/cache4 tmp/cache5 && mkdir -p tmp/cache tmp/cache1 tmp/cache2 tmp/cache3 tmp/cache4 tmp/cache5

    - name: Set up Configuration Files
      run: |
        cp config/config.yml.example config/config.yml
        cp config/database.yml.example config/database.yml
        cp config/sidekiq.yml.example config/sidekiq.yml
        cp config/credentials.json.example config/credentials.json
        cp config/sidekiq-test.yml.example config/sidekiq-test.yml

    - name: Build Docker Container
      run: |
        docker compose build
    - name: Run syntax checks
      run: |
        docker compose run api bash -c 'touch /tmp/no-syntax-errors && find app lib config -name *.rb -exec bash -c "ruby -c {} >/dev/null || rm /tmp/no-syntax-errors" ";" && ls /tmp/no-syntax-errors'
    - name: Run Container
      run: docker compose -f docker-compose.yml -f docker-test.yml up -d

    - name: Wait for the server to be ready
      run: |
        tail -f log/test.log &
        until curl --silent -I -f --fail http://localhost:3000 ; do printf .; sleep 1; done
    - name: Set up parallel environment
      run: docker compose exec -T api test/setup-parallel-env.sh

    - name: Precompile Assets
      run: docker compose exec -T api bundle exec rake assets:precompile

    - name: Prepare Parallel Runtime Log
      run: |
        sleep 10
        touch tmp/parallel_runtime_test.log
        chmod +w tmp/parallel_runtime_test.log

    - name: Run Unit Tests
      id: unit-tests
      env:
        TEST_RETRY_COUNT: 3
      run: |
        docker compose exec -e TEST_RETRY_COUNT=$TEST_RETRY_COUNT -T -e PATTERN='controllers contract' api test/run-tests.sh

    - name: After Unit Test
      env:
        GITHUB_EVENT: ${{ github.event_name}}
        GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TEST_RESULT: ${{ steps.unit-tests.outcome}}
        GITHUB_BUILD_NUMBER: ${{ github.run_number }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
        GITHUB_JOB_NAME: ${{ github.job }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        AWS_REGION: eu-west-1
      run:  |
        docker compose exec -T -e GIT_BRANCH=$GIT_BRANCH \
        -e GITHUB_EVENT=$GITHUB_EVENT \
        -e GITHUB_TEST_RESULT=$GITHUB_TEST_RESULT \
        -e GITHUB_REPO=$GITHUB_REPO \
        -e GITHUB_BUILD_NUMBER=$GITHUB_BUILD_NUMBER \
        -e GIT_COMMIT_SHA=$GITHUB_COMMIT_SHA \
        -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID \
        -e GITHUB_JOB_NAME=$GITHUB_JOB_NAME \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e ROLE_TO_ASSUME=$AWS_ROLE_TO_ASSUME \
        -e AWS_REGION=$AWS_REGION \
        -e AWS_CONFIG_FILE=/app/credentials api test/test-coverage.sh


  contract-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Enviroments
      run: |
        export RECORD_RUNTIME=true
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        export LANGUAGE=C.UTF-8
        export PATH=/root/.local/bin:$PATH
        rm -rf tmp/cache tmp/cache1 tmp/cache2 tmp/cache3 tmp/cache4 tmp/cache5 && mkdir -p tmp/cache tmp/cache1 tmp/cache2 tmp/cache3 tmp/cache4 tmp/cache5

    - name: Set up Configuration Files
      run: |
        cp config/config.yml.example config/config.yml
        cp config/database.yml.example config/database.yml
        cp config/sidekiq.yml.example config/sidekiq.yml
        cp config/credentials.json.example config/credentials.json
        cp config/sidekiq-test.yml.example config/sidekiq-test.yml

    - name: Build Docker Container
      run: |
        docker compose build

    - name: Run syntax checks
      run: |
        docker compose run api bash -c 'touch /tmp/no-syntax-errors && find app lib config -name *.rb -exec bash -c "ruby -c {} >/dev/null || rm /tmp/no-syntax-errors" ";" && ls /tmp/no-syntax-errors'

    - name: Run Container
      run: docker compose -f docker-compose.yml -f docker-test.yml up -d

    - name: Wait for the server to be ready
      run: |
        tail -f log/test.log &
        until curl --silent -I -f --fail http://localhost:3000 ; do printf .; sleep 1; done

    - name: Set up Parallel Environment
      run: docker compose exec -T api test/setup-parallel-env.sh

    - name: Precompile Assets
      run: docker compose exec -T api bundle exec rake assets:precompile

    - name: Prepare Parallel Runtime Log
      run: |
        sleep 10
        touch tmp/parallel_runtime_test.log
        chmod +w tmp/parallel_runtime_test.log

    - name: Run Contract Tests
      id: run-tests
      env:
        TEST_RETRY_COUNT: 3
      run: |
        docker compose exec -e TEST_RETRY_COUNT=$TEST_RETRY_COUNT -T -e PATTERN='controllers models mailers integration workers lib' api test/run-tests.sh

    - name: After Contract Test
      env:
        GITHUB_EVENT: ${{ github.event_name}}
        GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TEST_RESULT: ${{ steps.run-tests.outcome}}
        GITHUB_BUILD_NUMBER: ${{ github.run_number }}
        GITHUB_COMMIT_SHA: ${{ github.sha }}
        GITHUB_JOB_NAME: ${{ github.job }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        AWS_REGION: eu-west-1
      run:  |
        docker compose exec -T -e GIT_BRANCH=$GIT_BRANCH \
        -e GITHUB_EVENT=$GITHUB_EVENT \
        -e GITHUB_TEST_RESULT=$GITHUB_TEST_RESULT \
        -e GITHUB_REPO=$GITHUB_REPO  \
        -e GITHUB_BUILD_NUMBER=$GITHUB_BUILD_NUMBER \
        -e GIT_COMMIT_SHA=$GITHUB_COMMIT_SHA \
        -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID \
        -e GITHUB_JOB_NAME=$GITHUB_JOB_NAME \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e ROLE_TO_ASSUME=$AWS_ROLE_TO_ASSUME \
        -e AWS_REGION=$AWS_REGION \
        -e AWS_CONFIG_FILE=/app/credentials api test/test-coverage.sh
